### ISSUE TITLE
Data : Cannabalization Data.csv

### ISSUE THREAD

**Issue by datascienceforlife** [ibiggy9/cannibalization-predictor#1]
Hi, 
Can you please provide the Cannabalization Data.csv file or suggest the columns to use in orther to reproduce your study.
Thank you.

**Comment by ibiggy9** [comment]
No problem, I have uploaded a sample data set for you in the master branch.

**Comment by datascienceforlife** [comment]
Thank you ibiggy9, I also want to know what does tha variables Vol1, Vol2... refer to please, for reproductibility aim. Thank you

**Comment by ibiggy9** [comment]
Not a problem. Those numbers refer to revenues for various similar products made by the same company that launched the new product. This enables us to see, to some degree, the amount of sales the new innovation has taken from our other products. In practice, we temper the results with the delta in the total product category (crackers in this case), to understand if its true cannibalization or if the decreases/increases in other products is due to the total growth/decline in the overall category. 

Please note the data provided are samples and not accurate market data as that is proprietary to the company. 

Please let me know if you have any further questions.

**Comment by datascienceforlife** [comment]
It would be good to know what are the features needed to perform such study, if I understand, those are just revenues made by similar products in a given date, but not date of introduction of the new product that we aim to recognise if it cannibalizes other.

**Comment by ibiggy9** [comment]
Yes, so the earliest timelines selected were when the product "Veggie Crisps" was introduced to the market so that you can see changes to other products during that time. The reason that timelines before the product launch were not included in the dataset was that we don't have any earlier historical data by week at my company. So, checking deltas on annual revenues prior to our acquisition of weekly data was what I had to resort to which revealed insignificant growth year over year on most products (~1-2%) which makes sense for a slow/no-growth category. It's not a perfect approach but we had to use the data we had. 

Thanks for all your input. I do appreciate it.
